### ISSUE TITLE
use deployTarget instead of configurable environment

### ISSUE THREAD

**Issue by hellvinz** [ember-cli-deploy/ember-cli-deploy-build#21]
Hi,
It is now mandatory to pass an environment to ember-cli-deploy since https://github.com/ember-cli/ember-cli-deploy/commit/8f9b40d5b7afb2e3340694038eec31d867ae8085 and the passed value is being put in context.deployTarget.
before making a pull request, I would like to know what you'd think of using context.deployTarget value instead of the environment config option.
cheers,
Vincent

**Comment by kiwiupover** [comment]
@hellvinz I don't if the there is a straight correlation between deployTarget and the environment.

**Comment by lukemelia** [comment]
Departing build environment and deployTarget was a conscious choice that we are happy with. Is it causing an issue for you?

**Comment by hellvinz** [comment]
I felt that this was a sensible default, but I guess that's because of my rails/capistrano background. Since everything is configurable in config/deploy.js it's all fine for me.
thanks

**Comment by achambers** [comment]
Will close this issue now. Reopen if there is anything else to discuss
