### ISSUE TITLE
change outputPath

### ISSUE THREAD

**Issue by broerse** [ember-cli-deploy/ember-cli-deploy-build#22]
I am new to this and am writing a deploy for CouchDB. In my setup hook I like to extend the ENV.build.outputPath with `'/_attachments'` like this:

`outputPath = outputPath + path.sep + '_attachments';` 

How do I access the build outputPath?

**Comment by broerse** [comment]
I think I just have to return `outputPath` from my setup hook if you write:

```
outputPath: function(context) {
  return context.outputPath || 'tmp' + path.sep + 'deploy-dist';
},
```

Not sure....

**Comment by broerse** [comment]
Above works fine as log as you don't overwrite `outputPath` in deploy.js 
```
    ENV.build = {
      environment: 'production',
      outputPath: 'tmp/xxx'
    };
```

I see:
```
            return {
              distDir: outputPath,
```
Perhaps if this is changed to `distDir: distDir` and write something like this

```
     defaultConfig: {
        environment: 'production',
        outputPath: 'tmp' + path.sep + 'deploy-dist',
        distDir: function(context) {
          return context.distDir;
        }
     },

      setup: function() {
        var distDir = this.readConfig('distDir');
        var outputPath = this.readConfig('outputPath');
        return {
          distDir: outputPath
        };
      },
```
I can overwrite distDir from my plug-in.

**Comment by broerse** [comment]
Created PR that will fix this https://github.com/ember-cli-deploy/ember-cli-deploy-build/pull/23

**Comment by duizendnegen** [comment]
Closing this, ref. discussion in #23.
