### ISSUE TITLE
deploy command is invalid

### ISSUE THREAD

**Issue by Cerealkillerway** [ember-cli-deploy/ember-cli-deploy-build#24]
I've just installed the addon in my ember project, but once I type "ember deploy" I get the error:

The specified command deploy is invalid. For available options, see `ember help`.

(Ember 2.2.0, ember-cli 1.13.13)

**Comment by martinciu** [comment]
@Cerealkillerway I have the same issue. Did you solve it?

**Comment by Cerealkillerway** [comment]
sorry martinciu, I just can't remember exactly what was wrong, but I've closed this because in the end was not due to this plugin itself, but because I was doing something wrong.

**Comment by wereldbolt** [comment]
The error disappeared after installing ember-cli-deploy.
