### ISSUE TITLE
Ensure dist directory is removed before each build

### ISSUE THREAD

**Issue by altrim** [ember-cli-deploy/ember-cli-deploy-build#26]
The issue occurs if you are using [ember-cli-deploy-gzip](https://github.com/ember-cli-deploy/ember-cli-deploy-gzip).
If you run the build consequently - the second time if the fingerprint of a file didn't change the gzip plugin will run again over the already gzipped file and in turn it will double gzip that file which the browser can't decompress thus making the app break. 

A solution would be to delete the `dist` folder before each build.

**Comment by fivetanley** [comment]
@altrim This would be very handy to have, I am getting trolled constantly by this. Would you mind opening a PR with your commit?

**Comment by lukemelia** [comment]
@altrim @fivetanley this is due to a bug in tree-sync that was recently fixed https://github.com/stefanpenner/tree-sync/pull/1

**Comment by fivetanley** [comment]
@lukemelia Do you know where in the tree of dependencies tree-sync needs to be updated? I'm running the latest of everything (deploy, ember-cli, etc) as far as I know.

**Comment by lukemelia** [comment]
@fivetanley According to @rwjblue [here](https://github.com/ember-cli/ember-cli/issues/5445#issuecomment-184356498), `rm -rf node_modules && npm install` should get the updated version.
