### ISSUE TITLE
buildEnv vs deployTarget confusion

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli-deploy/ember-cli-deploy-build#28]
The log message at

https://github.com/ember-cli-deploy/ember-cli-deploy-build/blob/master/index.js#L33

should either say it's the deployTarget or should print out the build environment.

**Comment by lukemelia** [comment]
As far as I can see, that message is printing out the build environment and describes it as `buildEnv`. I'm not sure what we would change. Let me know if I misunderstood your issue.

**Comment by Gaurav0** [comment]
It doesn't appear to be. When I deploy Ember Twiddle it prints:

    |    - building app to `tmp/deploy-dist` using buildEnv `staging`...

See https://travis-ci.org/ember-cli/ember-twiddle/builds/116922632 line 723 (need to open after_script)

I do not have a `staging` environment but do have a `staging` deployTarget

**Comment by Gaurav0** [comment]
Never mind, I am passing deployTarget as environment in config/deploy.js Sorry to waste your time.
