### ISSUE TITLE
.htaccess is not included in the distFiles

### ISSUE THREAD

**Issue by varoot** [ember-cli-deploy/ember-cli-deploy-build#29]
I'm not sure if this is intentional or a bug. To fix this, we just need to add `dot: true` to `glob.sync` options. The downside of this would be that other OS files (like `.DS_Store`) will also be included in the list of files. I can make a PR but I'd like to know your thoughts on this.

**Comment by lukemelia** [comment]
This is not intentional. I think we should err on the side of inclusion and would gladly accept a PR. Thanks @varoot.

**Comment by blimmer** [comment]
I also experienced something similar with the `.well-known` directory.

**Comment by blimmer** [comment]
@lukemelia it seems like maybe ember-cli should be returning it from the builder in the `files` array. Do you think we should try to fix this here or upstream?

**Comment by bevinhex** [comment]
tested with ember-cli-deploy-simply-ssh deployment, my .htaccess file went to server nicely.

**Comment by lukemelia** [comment]
Fixed by #55
