### ISSUE TITLE
DEPRECATION to fix: ember-cli/ext/promise

### ISSUE THREAD

**Issue by johnunclesam** [ember-cli-deploy/ember-cli-deploy-build#37]
```
DEPRECATION: `ember-cli/ext/promise` is deprecated, use `rsvp` instead. Required here:
  Object.<anonymous> (\node_modules\ember-cli-deploy-build\index.js:4:15)
```

**Comment by lukemelia** [comment]
Will be addressed by #36

**Comment by bgentry** [comment]
Looks like this was closed by #36. Not yet published, though.

**Comment by lukemelia** [comment]
@johnunclesam @bgentry fix released in 1.0.0.beta.0. Can you verify this addresses the issue for you?

**Comment by johnunclesam** [comment]
@lukemelia, no. The same deprecations.

**Comment by bgentry** [comment]
@lukemelia yes, I can confirm that with updates to v1.0.0-beta.0 of these packages:
* ember-cli-deploy-build
* ember-cli-deploy-gzip
* ember-cli-deploy-manifest
* ember-cli-deploy-s3

and an update to ember-cli-deploy-cloudfront, I receive no more deprecation errors. I did have to ditch ember-cli-deploy-s3-pack and install each of the deps manually to test it (since these are pre-release npm packages), but once I did that it worked 👏

**Comment by lukemelia** [comment]
@bgentry thanks for confirming. You or I can PR s3-pack now or wait until I publish 1.0.0 proper.

@johnunclesam Can you share the contents of your package.json and the deprecations output you are seeing?

**Comment by johnunclesam** [comment]
Sorry, @lukemelia, I just updated in my package.json the `ember-cli-deploy-build` to beta. Didn't try all packages. Maybe this is the problem.

**Comment by jelhan** [comment]
Updating ember-cli-deploy-build to v1.0.0-beta.0 fixed the deprecation mentioned above for me. I did not had to update any other package.

**Comment by johnunclesam** [comment]
I still have the problem.

My **package.json**:
```
...
"ember-cli-deploy": "^1.0.0",
...
```

yarn run good, in node_modules I have ember-cli-deploy folder with 1.0.0 version.

When I launch `ember s` it gives to me:

```
DEPRECATION: `ember-cli/ext/promise` is deprecated, use `rsvp` instead. Required here:
  Object.<anonymous> (D:\app\node_modules\ember-cli-deploy-build\index.js:4:15)
DEPRECATION: `ember-cli/ext/promise` is deprecated, use `rsvp` instead. Required here:
  Object.<anonymous> (D:\app\node_modules\ember-cli-deploy-revision-data\index.js:4:15)
WARNING: Node v7.9.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js.
Livereload server on http://localhost:49153
Serving on http://localhost:4200/

Build successful - 26290ms.
```

**Comment by lukemelia** [comment]
Hi @johnunclesam, it looks like you gave me the version information for `ember-cli-deploy`. The deprecations are coming from two of your installed plugins, ember-cli-deploy-build and ember-cli-depoy-revision-data. Those would have their own entries in your package.json file (or they might be referenced via a plugin pack). Both of those plugins have 1.0.0 versions released which address this deprecation warning. I hope that helps!

**Comment by johnunclesam** [comment]
Sorry. Thanks. The plugin is: `"ember-cli-deploy-firebase-pack": "^0.3.1"`
