### ISSUE TITLE
Generated source maps are binary files

### ISSUE THREAD

**Issue by sdhull** [ember-cli-deploy/ember-cli-deploy-build#41]
When doing `ember build --prod`, the generated source maps (in `dist/assets`) are json files (as they should be).

However, the result from `ember deploy`, the generated source maps (in `tmp/deploy-dist/assets`) are binary files (which are unparsable by source map libraries).

I have no idea how to go about debugging. Any help would be appreciated.

**Comment by sdhull** [comment]
Note: (obviously) I have enabled source map generation regardless of environment

**Comment by achambers** [comment]
@sdhull Do you have the -gzip plugin installed? I suspect what you’re seeing is that plugin compressing your source map files. In which case it comes down to your configuration and not this plugin.

**Comment by achambers** [comment]
@sdhull I suspect you need to add your source maps to this config prop of -gzip

https://github.com/ember-cli-deploy/ember-cli-deploy-gzip/blob/master/README.md#ignorepattern

Please let me know if this solves your situation so we can close this issue.

**Comment by sdhull** [comment]
Yeah you're correct thanks for your help!! I was truly stumped.
