### ISSUE TITLE
How to re-use output file from ember build

### ISSUE THREAD

**Issue by haoliangyu** [ember-cli-deploy/ember-cli-deploy-build#66]
Is it possible to skip the build with a flag? For example,

```
# build the app
ember build

# do other sutff

# deploy the app directly, no need to build again
ember deploy --skip-build
```

The use case is that I want to skip the redundant build in my CI/CD pipeline, but still keep the default build-and-deploy behavior in all other scenario.

**Comment by haoliangyu** [comment]
I can use the EMBER_CLI_DEPLOY_REUSE_BUILD variable to achieve this.

**Comment by haoliangyu** [comment]
I am trying to the following steps:

```
$ ember build
$ EMBER_CLI_DEPLOY_REUSE_BUILD=true ember deploy
```

but the ember deploy command throws the error

```
Error: ENOENT: no such file or directory, open 'tmp/deploy-dist/status.json'
```

Is there anything I missed?

**Comment by achambers** [comment]
`ember build` builds to `dist‘. 

`ember deploy‘ builds to `tmp-dist`. 

So, there is no previous build dir as far as ember-cli-deploy is concerned, in that example.

**Comment by achambers** [comment]
@haoliangyu So, if you want to run the above two steps, you’ll need to use the `-o` flag with the `ember build` command to use the same dist dir as the deploy command. 

I’m going to close this now. If you have other questions, let us know here or in the `ec-deploy` channel on Discord
